apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
    spec:
      containers:
      - name: sampleapi
        image: azurecontainertestjintoregistry.azurecr.io/sampleapi/sampleapi:latest
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: sampleapi-config
        - secretRef:
            name: sampleapi-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"